# Generated by Django 5.0.2 on 2024-02-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_cartitems_cart_order_orderitem_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transection_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.profile'),
        ),
    ]
